---

- name: create prometheus group
  ansible.builtin.group:
    name: prometheus
    state: present

- name: create prometheus user
  ansible.builtin.user:
    name: prometheus
    group: prometheus
    create_home: false
    shell: /bin/false
    state: present

- name: Create required dirs
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
  - /etc/prometheus
  - /var/lib/prometheus
  - /etc/prometheus/rules
  - /etc/prometheus/rules.d
  - /etc/prometheus/files_sd
#- name: down prometheus
#  ansible.builtin.get_url:
#    url: '{{ prometheus_url }}/{{ prometheus_version  }}/{{ prometheus_package }}'
#    dest: /tmp

- name: uncompress prometheus
  ansible.builtin.unarchive:
    remote_src: true 
    src: '{{ prometheus_url }}/{{ prometheus_version  }}/{{ prometheus_package }}.tar.gz'
    dest: /tmp/

- name: copy console files to /etc
  ansible.builtin.copy:
    remote_src: yes
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: prometheus
    group: prometheus
    mode: '{{ item.mode }}'
  loop:
  - src: /tmp/{{ prometheus_package }}/consoles
    dest: /etc/prometheus/
    mode: '0755'
  - src: /tmp/{{ prometheus_package }}/console_libraries
    dest: /etc/prometheus/
    mode: '0755'
  - src: /tmp/{{ prometheus_package }}/prometheus.yml
    dest: /etc/prometheus/
    mode: '0644'
  - src: /tmp/{{ prometheus_package }}/prometheus
    dest: /usr/local/bin/
    mode: '0755'
  - src: /tmp/{{ prometheus_package }}/promtool
    dest: /usr/local/bin/
    mode: '0755'

- name: copy prometheus service file
  ansible.builtin.copy:
    src: '{{ role_path }}/files/prometheus.service'
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  ignore_errors: yes


- name: start and enable the prometheous service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: prometheous
    enabled: true
...
