---

- name: create prometheus group
  ansible.builtin.group:
    name: prometheus
    state: present

- name: create prometheus user
  ansible.builtin.user:
    name: prometheus
    group: prometheus
    create_home: false
    shell: /bin/false
    state: present

- name: Create required dirs
  ansible.builtin.file:
    path: '{{ item.path  }}'
    state: directory
    mode: '{{ item.mode }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'

  loop:
  - path: /etc/prometheus
    owner: root
    group: root
    mode: 755
  - path: /var/lib/prometheus
    owner: prometheus
    group: prometheus
    mode: 755

#- name: down prometheus
#  ansible.builtin.get_url:
#    url: '{{ prometheus_url }}/{{ prometheus_version  }}/{{ prometheus_package }}'
#    dest: /tmp

- name: uncompress prometheus
  ansible.builtin.unarchive:
    remote_src: true 
    src: '{{ prometheus_url }}/{{ prometheus_version  }}/{{ prometheus_package }}'
    dest: /tmp/

- name: copy console files to /etc
  ansible.builtin.copy:
    remote_src: yes
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: prometheus
    group: prometheus
  loop:
  - src: /tmp/{{ (prometheus_package | split('.'))[0] }}/consoles
    dest: /etc/prometheus/

  - src: /tmp/{{ (prometheus_package|split('.'))[0] }}/console_libraries
    dest: /etc/prometheus/

...
